package sample;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kaakaa_hoe' at '14/06/28 21:17' with Gradle 1.9
 *
 * @author kaakaa_hoe, @date 14/06/28 21:17
 */
public class Stab {
    public boolean someLibraryMethod() {
        return true;
    }
}
